import { selector_cantidades } from "./components.js";

export const SCREEN_RESPONSES = {
  Inicio: {
    screen: "Inicio",
    data: {
      Hamburguesas: false,
      Perros: false,
      Choripapas: false,
      Pollos: false,
      Carnes: false,
      Picadas: false,
    },
  },

  Productos: {
    screen: "Productos",
    data: {
      Hamburguesas: false,
      Perros: false,
      Choripapas: false,
      Pollos: false,
      Carnes: false,
      Picadas: false,
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_ham_7: false,
      chk_ham_8: false,
      chk_ham_9: false,
      chk_ham_10: false,
      chk_ham_11: false,
      chk_ham_12: false,
      chk_ham_13: false,
      chk_ham_14: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_cho_1: false,
      chk_cho_2: false,
      chk_cho_3: false,
      chk_cho_4: false,
      chk_pollo_1: false,
      chk_pollo_2: false,
      chk_pollo_3: false,
      chk_carne_1: false,
      chk_carne_2: false,
      chk_pic_1: false,
      chk_pic_2: false,
    },
  },

  Cantidades: {
    screen: "Cantidades",
    data: {
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_ham_7: false,
      chk_ham_8: false,
      chk_ham_9: false,
      chk_ham_10: false,
      chk_ham_11: false,
      chk_ham_12: false,
      chk_ham_13: false,
      chk_ham_14: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_cho_1: false,
      chk_cho_2: false,
      chk_cho_3: false,
      chk_cho_4: false,
      chk_pollo_1: false,
      chk_pollo_2: false,
      chk_pollo_3: false,
      chk_carne_1: false,
      chk_carne_2: false,
      chk_pic_1: false,
      chk_pic_2: false,
      selector_cantidades,
    },
  },

  Bebidas: {
    screen: "Bebidas",
    data: {
      chk_beb_1: false,
      chk_beb_2: false,
      chk_beb_3: false,
      chk_beb_4: false,
      chk_beb_5: false,
      chk_beb_6: false,
      chk_beb_7: false,
      chk_beb_8: false,
      chk_beb_9: false,
      chk_beb_10: false,
      chk_beb_11: false,
      chk_beb_12: false,
      chk_beb_13: false,
      chk_beb_14: false,
      chk_beb_15: false,
      chk_beb_16: false,
      chk_beb_17: false,
      chk_beb_18: false,
      selector_cantidades,
    },
  },

  Resumen: {
    screen: "Resumen",
    data: {},
  },

  Formulario: {
    screen: "Formulario",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
