import { selector_cantidades } from "./components.js";

export const SCREEN_RESPONSES = {
  Inicio: {
    screen: "Inicio",
    data: {
      desayunos: false,
      arepas: false,
      comidas_rapidas: false,
      hamburguesas: false,
      perros_calientes: false,
      pizzas: false,
      especiales: false,
      combos: false,
    },
  },

  Productos: {
    screen: "Productos",
    data: {
      desayunos: false,
      arepas: false,
      comidas_rapidas: false,
      hamburguesas: false,
      perros_calientes: false,
      pizzas: false,
      especiales: false,
      combos: false,
      chk_des_1: false,
      chk_des_2: false,
      chk_des_3: false,
      chk_des_4: false,
      chk_des_5: false,
      chk_des_6: false,
      chk_des_7: false,
      chk_des_8: false,
      chk_des_9: false,
      chk_des_10: false,
      chk_des_11: false,
      chk_des_12: false,
      chk_des_13: false,
      chk_des_14: false,
      chk_des_15: false,
      chk_des_16: false,
      chk_des_17: false,
      chk_des_18: false,
      chk_des_19: false,
      chk_des_20: false,
      chk_des_21: false,
      chk_des_22: false,
      chk_des_23: false,
      chk_des_24: false,
      chk_des_25: false,
      chk_des_26: false,
      chk_are_1: false,
      chk_are_2: false,
      chk_are_3: false,
      chk_are_4: false,
      chk_are_5: false,
      chk_are_6: false,
      chk_fast_1: false,
      chk_fast_2: false,
      chk_fast_3: false,
      chk_fast_4: false,
      chk_fast_5: false,
      chk_fast_6: false,
      chk_fast_7: false,
      chk_fast_8: false,
      chk_fast_9: false,
      chk_fast_10: false,
      chk_fast_11: false,
      chk_fast_12: false,
      chk_fast_13: false,
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_dog_5: false,
      chk_esp_1: false,
      chk_esp_2: false,
      chk_esp_3: false,
      chk_esp_4: false,
      chk_esp_5: false,
      chk_esp_6: false,
      chk_esp_7: false,
      chk_esp_8: false,
      chk_combo_1: false,
      chk_combo_2: false,
      chk_combo_3: false,
      chk_combo_4: false,
      chk_combo_5: false,
      chk_pizza_1: false,
      chk_pizza_2: false,
      chk_pizza_3: false,
      chk_pizza_4: false,
      chk_pizza_5: false,

      sabores_pizza: [
        {
          id: "1",
          title: "Hawaiana",
          description: "Piña, Jamón.",
        },
        {
          id: "2",
          title: "Mexicana",
          description: "Boloñesa, pico e gallo y totopos.",
        },
        {
          id: "3",
          title: "Salami",
          description: "Jamón y salami.",
        },
        {
          id: "4",
          title: "Carnes Frias",
          description: "Chorizo, maíz, carne desmechada y boloñeza.",
        },
        {
          id: "5",
          title: "Criolla",
          description: "Tocineta, maíz, chorizo y cebolla.",
        },
        {
          id: "6",
          title: "Ranchera",
          description: "Tocineta, maíz, chorizo y cebolla.",
        },
        {
          id: "7",
          title: "Pollo Champiñones",
          description: "Pollo con champiñones.",
        },
      ],

      porciones_pizza: [
        {
          id: "familiar",
          title: "Familiar 50x50 cm",
          metadata: "$60.000",
        },
        {
          id: "mediana",
          title: "Mediana 40x40 cm",
          metadata: "$38.000",
        },
        {
          id: "pizzeta",
          title: "Pizzeta 22x22 cm",
          metadata: "$15.000",
        },
        {
          id: "porción",
          title: "Porción",
          metadata: "$8.000",
        },
      ],
    },
  },

  Cantidades: {
    screen: "Cantidades",
    data: {
      chk_des_1: false,
      chk_des_2: false,
      chk_des_3: false,
      chk_des_4: false,
      chk_des_5: false,
      chk_des_6: false,
      chk_des_7: false,
      chk_des_8: false,
      chk_des_9: false,
      chk_des_10: false,
      chk_des_11: false,
      chk_des_12: false,
      chk_des_13: false,
      chk_des_14: false,
      chk_des_15: false,
      chk_des_16: false,
      chk_des_17: false,
      chk_des_18: false,
      chk_des_19: false,
      chk_des_20: false,
      chk_des_21: false,
      chk_des_22: false,
      chk_des_23: false,
      chk_des_24: false,
      chk_des_25: false,
      chk_des_26: false,
      chk_are_1: false,
      chk_are_2: false,
      chk_are_3: false,
      chk_are_4: false,
      chk_are_5: false,
      chk_are_6: false,
      chk_fast_1: false,
      chk_fast_2: false,
      chk_fast_3: false,
      chk_fast_4: false,
      chk_fast_5: false,
      chk_fast_6: false,
      chk_fast_7: false,
      chk_fast_8: false,
      chk_fast_9: false,
      chk_fast_10: false,
      chk_fast_11: false,
      chk_fast_12: false,
      chk_fast_13: false,
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_dog_5: false,
      chk_esp_1: false,
      chk_esp_2: false,
      chk_esp_3: false,
      chk_esp_4: false,
      chk_esp_5: false,
      chk_esp_6: false,
      chk_esp_7: false,
      chk_esp_8: false,
      chk_combo_1: false,
      chk_combo_2: false,
      chk_combo_3: false,
      chk_combo_4: false,
      chk_combo_5: false,
      selector_cantidades,
    },
  },

  Bebidas: {
    screen: "Bebidas",
    data: {
      chk_beb_1: false,
      chk_beb_2: false,
      chk_beb_3: false,
      chk_beb_4: false,
      chk_beb_5: false,
      chk_beb_6: false,
      chk_beb_7: false,
      chk_beb_8: false,
      chk_beb_9: false,
      chk_beb_10: false,
      chk_beb_11: false,
      chk_beb_12: false,
      chk_beb_13: false,
      chk_beb_14: false,
      chk_beb_15: false,
      chk_beb_16: false,
      chk_beb_17: false,
      chk_beb_18: false,
      chk_beb_19: false,
      chk_beb_20: false,
      chk_beb_21: false,
      chk_beb_22: false,
      chk_beb_23: false,
      selector_cantidades,
    },
  },

  Resumen: {
    screen: "Resumen",
    data: {},
  },

  Formulario: {
    screen: "Formulario",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
