import { selector_cantidades } from "./components.js";

export const SCREEN_RESPONSES = {
  Inicio: {
    screen: "Inicio",
    data: {
      Hamburguesas: false,
      Sandwiches: false,
      "Hot Dogs": false,
      Parrilla: false,
      Ahumados: false,
      Horneadas: false,
      Entradas: false,
    },
  },

  Productos: {
    screen: "Productos",
    data: {
      Entradas: false,
      Hamburguesas: false,
      Sandwiches: false,
      Hotdogs: false,
      Parrilla: false,
      Ahumados: false,
      Horneadas: false,
      chk_ent_1: false,
      chk_ent_2: false,
      chk_ent_3: false,
      chk_ent_4: false,
      chk_ent_5: false,
      chk_ent_6: false,
      chk_ent_7: false,
      chk_ent_8: false,
      chk_ent_9: false,
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_ham_7: false,
      chk_ham_8: false,
      chk_ham_9: false,
      chk_ham_10: false,
      chk_ham_11: false,
      chk_ham_12: false,
      chk_ham_13: false,
      chk_ham_14: false,
      chk_ham_15: false,
      chk_ham_16: false,
      chk_ham_17: false,
      chk_ham_18: false,
      chk_ham_19: false,
      chk_ham_20: false,
      chk_ham_21: false,
      chk_ham_22: false,
      chk_ham_23: false,
      chk_ham_24: false,
      chk_sand_1: false,
      chk_sand_2: false,
      chk_sand_3: false,
      chk_sand_4: false,
      chk_sand_5: false,
      chk_sand_6: false,
      chk_sand_7: false,
      chk_sand_8: false,
      chk_sand_9: false,
      chk_sand_10: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_dog_5: false,
      chk_dog_6: false,
      chk_dog_7: false,
      chk_dog_8: false,
      chk_dog_9: false,
      chk_dog_10: false,
      chk_dog_11: false,
      chk_dog_12: false,
      chk_dog_13: false,
      chk_dog_14: false,
      chk_par_1: false,
      chk_par_2: false,
      chk_par_3: false,
      chk_par_4: false,
      chk_par_5: false,
      chk_par_6: false,
      chk_par_7: false,
      chk_par_8: false,
      chk_par_9: false,
      chk_par_10: false,
      chk_par_11: false,
      chk_par_12: false,
      chk_par_13: false,
      chk_par_14: false,
      chk_par_15: false,
      chk_par_16: false,
      chk_par_17: false,
      chk_par_18: false,
      chk_par_19: false,
      chk_par_20: false,
      chk_par_21: false,
      chk_par_22: false,
      chk_par_23: false,
      chk_par_24: false,
      chk_par_25: false,
      chk_ahu_1: false,
      chk_ahu_2: false,
      chk_ahu_3: false,
      chk_hor_1: false,
      chk_hor_2: false,
      chk_hor_3: false,
      chk_hor_4: false,
    },
  },

  Cantidades: {
    screen: "Cantidades",
    data: {
      chk_ent_1: false,
      chk_ent_2: false,
      chk_ent_3: false,
      chk_ent_4: false,
      chk_ent_5: false,
      chk_ent_6: false,
      chk_ent_7: false,
      chk_ent_8: false,
      chk_ent_9: false,
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_ham_7: false,
      chk_ham_8: false,
      chk_ham_9: false,
      chk_ham_10: false,
      chk_ham_11: false,
      chk_ham_12: false,
      chk_ham_13: false,
      chk_ham_14: false,
      chk_ham_15: false,
      chk_ham_16: false,
      chk_ham_17: false,
      chk_ham_18: false,
      chk_ham_19: false,
      chk_ham_20: false,
      chk_ham_21: false,
      chk_ham_22: false,
      chk_ham_23: false,
      chk_ham_24: false,
      chk_sand_1: false,
      chk_sand_2: false,
      chk_sand_3: false,
      chk_sand_4: false,
      chk_sand_5: false,
      chk_sand_6: false,
      chk_sand_7: false,
      chk_sand_8: false,
      chk_sand_9: false,
      chk_sand_10: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_dog_5: false,
      chk_dog_6: false,
      chk_dog_7: false,
      chk_dog_8: false,
      chk_dog_9: false,
      chk_dog_10: false,
      chk_dog_11: false,
      chk_dog_12: false,
      chk_dog_13: false,
      chk_dog_14: false,
      chk_par_1: false,
      chk_par_2: false,
      chk_par_3: false,
      chk_par_4: false,
      chk_par_5: false,
      chk_par_6: false,
      chk_par_7: false,
      chk_par_8: false,
      chk_par_9: false,
      chk_par_10: false,
      chk_par_11: false,
      chk_par_12: false,
      chk_par_13: false,
      chk_par_14: false,
      chk_par_15: false,
      chk_par_16: false,
      chk_par_17: false,
      chk_par_18: false,
      chk_par_19: false,
      chk_par_20: false,
      chk_par_21: false,
      chk_par_22: false,
      chk_par_23: false,
      chk_par_24: false,
      chk_ahu_1: false,
      chk_ahu_2: false,
      chk_ahu_3: false,
      chk_hor_1: false,
      chk_hor_2: false,
      chk_hor_3: false,
      chk_hor_4: false,
      selector_cantidades,
    },
  },

  Adicionales: {
    screen: "Adicionales",
    data: {
      chk_ad_queso: false,
      chk_ad_champinones: false,
      chk_ad_pina: false,
      chk_ad_arroz: false,
      chk_ad_cebolla: false,
      chk_ad_jalapenos: false,
      chk_ad_maicitos: false,
      chk_ad_maduritos: false,
      chk_ad_salchicha: false,
      selector_cantidades,
    },
  },

  Bebidas: {
    screen: "Bebidas",
    data: {
      chk_beb_1: false,
      chk_beb_2: false,
      chk_beb_3: false,
      chk_beb_4: false,
      chk_beb_5: false,
      chk_beb_6: false,
      chk_beb_7: false,
      chk_beb_8: false,
      chk_beb_9: false,
      chk_beb_10: false,
      chk_beb_11: false,
      chk_beb_12: false,
      chk_beb_13: false,
      selector_cantidades,
    },
  },

  Resumen: {
    screen: "Resumen",
    data: {},
  },

  Formulario: {
    screen: "Formulario",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
