export const productos = {
  "Chicharrón Carnudo": 17000,
  "Papas Cheddar": 14900,
  "Chorizo con Papa": 12900,
  "4x2 Alitas": 15900,
  "8x2 Alitas": 28900,
  "16x2 Alitas": 59900,
  "Golden Whisky": 10,
  "Sr Smith": "${form.Sr Smith[0]}",
  "Pig Premium": "${form.Pig Premium[0]}",
  "Sra Smith": "${form.Sra Smith[0]}",
  "Cheese Burger": "${form.Cheese Burger[0]}",
  "Cheese Bacon": "${form.Cheese Bacon[0]}",
  "Mr Pollo": "${form.Mr Pollo[0]}",
  "Mr Costillas": "${form.Mr Costillas[0]}",
  "Mr Mexicana": "${form.Mr Mexicana[0]}",
  "Mr Hawaiana": "${form.Mr Hawaiana[0]}",
  "Mr Madurita": "${form.Mr Madurita[0]}",
  "Mr Campesina": "${form.Mr Campesina[0]}",
  "Mr Tocimaiz": "${form.Mr Tocimaiz[0]}",
  "Mr Doritos": "${form.Mr Doritos[0]}",
  "Burger Fest": "${form.Burger Fest[0]}",
  "Hot Dog Costillas": "${form.Hot Dog Costillas[0]}",
  "Hot Dog Clásico": "${form.Hot Dog Clásico[0]}",
  "Hot Dog Cheese Bacon": "${form.Hot Dog Cheese Bacon[0]}",
  "Hot Dog Mr Hawaiano": "${form.Hot Dog Mr Hawaiano[0]}",
  "Hot Dog Mr Mexicano": "${form.Hot Dog Mr Mexicano[0]}",
  "Mazorcada Clásica": "${form.Mazorcada Clásica[0]}",
  "Mazorcada Mega Quesos": "${form.Mazorcada Mega Quesos[0]}",
  "Mazorcada Super Carnes": "${form.Mazorcada Super Carnes[0]}",
  "Mazorcada Chicharrona": "${form.Mazorcada Chicharrona[0]}",
};

export const adicionales = {
  "Papa criolla": "${form.can_ad_papas_1[0]} ",
  "Papa francesa": "${form.can_ad_papas_2[0]} ",
  "Papa en casco artesanal": "${form.can_ad_papas_3[0]} ",
};
