import { selector_cantidades } from "./components.js";

export const SCREEN_RESPONSES = {
  Inicio: {
    screen: "Inicio",
    data: {
      Entradas: false,
      "2x1_Alitas": false,
      Hamburguesas: false,
      Hot_Dogs: false,
      Mazorcadas: false,
    },
  },

  Productos: {
    screen: "Productos",
    data: {
      Entradas: false,
      "2x1_Alitas": false,
      Mazorcadas: false,
      Hamburguesas: false,
      Hot_Dogs: false,
      chk_ent_1: false,
      chk_ent_2: false,
      chk_ent_3: false,
      chk_ala_1: false,
      chk_ala_2: false,
      chk_ala_3: false,
      chk_maz_1: false,
      chk_maz_2: false,
      chk_maz_3: false,
      chk_maz_4: false,
      chk_maz_5: false,
      chk_maz_6: false,
      chk_maz_7: false,
      chk_maz_8: false,
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_ham_7: false,
      chk_ham_8: false,
      chk_ham_9: false,
      chk_ham_10: false,
      chk_ham_11: false,
      chk_ham_12: false,
      chk_ham_13: false,
      chk_ham_14: false,
      chk_ham_15: false,
      chk_ham_16: false,
      chk_ham_17: false,
      chk_ham_18: false,
      chk_ham_19: false,
      chk_ham_20: false,
      chk_ham_21: false,
      chk_ham_22: false,
      chk_ham_23: false,
      chk_ham_24: false,
      chk_ham_25: false,
      chk_ham_26: false,
      chk_ham_27: false,
      chk_ham_28: false,
      chk_ham_29: false,
      chk_ham_30: false,
      chk_ham_31: false,
      chk_ham_32: false,
      chk_ham_33: false,
      chk_ham_34: false,
      chk_ham_35: false,
      chk_ham_36: false,
      chk_ham_37: false,
      chk_ham_38: false,
      chk_ham_39: false,
      chk_ham_40: false,
      chk_ham_41: false,
      chk_ham_42: false,
      chk_ham_43: false,
      chk_ham_44: false,
      chk_ham_45: false,
      chk_ham_46: false,
      chk_ham_47: false,
      chk_ham_48: false,
      chk_ham_49: false,
      chk_ham_50: false,
      chk_ham_51: false,
      chk_ham_52: false,
      chk_ham_53: false,
      chk_ham_54: false,
      chk_ham_55: false,
      chk_ham_56: false,
      chk_ham_57: false,
      chk_ham_58: false,
      chk_ham_59: false,
      chk_ham_60: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_dog_5: false,
      chk_dog_6: false,
      chk_dog_7: false,
      chk_dog_8: false,
      chk_dog_9: false,
      chk_dog_10: false,
    },
  },

  Cantidades: {
    screen: "Cantidades",
    data: {
      chk_ent_1: false,
      chk_ent_2: false,
      chk_ent_3: false,
      chk_ala_1: false,
      chk_ala_2: false,
      chk_ala_3: false,
      chk_maz_1: false,
      chk_maz_2: false,
      chk_maz_3: false,
      chk_maz_4: false,
      chk_maz_5: false,
      chk_maz_6: false,
      chk_maz_7: false,
      chk_maz_8: false,
      chk_ham_1: false,
      chk_ham_2: false,
      chk_ham_3: false,
      chk_ham_4: false,
      chk_ham_5: false,
      chk_ham_6: false,
      chk_ham_7: false,
      chk_ham_8: false,
      chk_ham_9: false,
      chk_ham_10: false,
      chk_ham_11: false,
      chk_ham_12: false,
      chk_ham_13: false,
      chk_ham_14: false,
      chk_ham_15: false,
      chk_ham_16: false,
      chk_ham_17: false,
      chk_ham_18: false,
      chk_ham_19: false,
      chk_ham_20: false,
      chk_ham_21: false,
      chk_ham_22: false,
      chk_ham_23: false,
      chk_ham_24: false,
      chk_ham_25: false,
      chk_ham_26: false,
      chk_ham_27: false,
      chk_ham_28: false,
      chk_ham_29: false,
      chk_ham_30: false,
      chk_ham_31: false,
      chk_ham_32: false,
      chk_ham_33: false,
      chk_ham_34: false,
      chk_ham_35: false,
      chk_ham_36: false,
      chk_ham_37: false,
      chk_ham_38: false,
      chk_ham_39: false,
      chk_ham_40: false,
      chk_ham_41: false,
      chk_ham_42: false,
      chk_ham_43: false,
      chk_ham_44: false,
      chk_ham_45: false,
      chk_ham_46: false,
      chk_ham_47: false,
      chk_ham_48: false,
      chk_ham_49: false,
      chk_ham_50: false,
      chk_ham_51: false,
      chk_ham_52: false,
      chk_ham_53: false,
      chk_ham_54: false,
      chk_ham_55: false,
      chk_ham_56: false,
      chk_ham_57: false,
      chk_ham_58: false,
      chk_ham_59: false,
      chk_ham_60: false,
      chk_dog_1: false,
      chk_dog_2: false,
      chk_dog_3: false,
      chk_dog_4: false,
      chk_dog_5: false,
      chk_dog_6: false,
      chk_dog_7: false,
      chk_dog_8: false,
      chk_dog_9: false,
      chk_dog_10: false,
      selector_cantidades,
    },
  },

  Adicionales: {
    screen: "Adicionales",
    data: {
      chk_ad_papas_1: false,
      chk_ad_papas_2: false,
      chk_ad_papas_3: false,
      selector_cantidades,
    },
  },

  Resumen: {
    screen: "Resumen",
    data: {},
  },

  Formulario: {
    screen: "Formulario",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
