import { selector_cantidades } from "./components.js";

export const SCREEN_RESPONSES = {
  Inicio: {
    screen: "Inicio",
    data: {
      Hamburguesas: false,
      Pizzas: false,
      Choripan: false,
      Alitas: false,
      Picadas: false,
      Especiales: false,
    },
  },

  Productos: {
    screen: "Productos",
    data: {
      Hamburguesas: false,
      Pizzas: false,
      Choripan: false,
      Alitas: false,
      Picadas: false,
      Especiales: false,
      chk_bur_1: false,
      chk_bur_2: false,
      chk_bur_3: false,
      chk_bur_4: false,
      chk_bur_5: false,
      chk_bur_6: false,
      chk_bur_7: false,
      chk_piz_1: false,
      chk_piz_2: false,
      chk_piz_3: false,
      chk_cho_1: false,
      chk_cho_2: false,
      chk_ala_1: false,
      chk_ala_2: false,
      chk_ala_3: false,
      chk_ala_4: false,
      chk_ala_5: false,
      chk_ala_6: false,
      chk_pic_1: false,
      chk_pic_2: false,
      chk_pic_3: false,
      chk_pic_4: false,
      chk_esp_1: false,
      chk_esp_2: false,
      chk_esp_3: false,
      chk_esp_4: false,
      chk_esp_5: false,
      chk_esp_6: false,
      chk_esp_7: false,
      chk_esp_8: false,
      chk_esp_9: false,
      chk_esp_10: false,
    },
  },

  Cantidades: {
    screen: "Cantidades",
    data: {
      chk_bur_1: false,
      chk_bur_2: false,
      chk_bur_3: false,
      chk_bur_4: false,
      chk_bur_5: false,
      chk_bur_6: false,
      chk_bur_7: false,
      chk_piz_1: false,
      chk_piz_2: false,
      chk_piz_3: false,
      chk_cho_1: false,
      chk_cho_2: false,
      chk_ala_1: false,
      chk_ala_2: false,
      chk_ala_3: false,
      chk_ala_4: false,
      chk_ala_5: false,
      chk_ala_6: false,
      chk_pic_1: false,
      chk_pic_2: false,
      chk_pic_3: false,
      chk_pic_4: false,
      chk_esp_1: false,
      chk_esp_2: false,
      chk_esp_3: false,
      chk_esp_4: false,
      chk_esp_5: false,
      chk_esp_6: false,
      chk_esp_7: false,
      chk_esp_8: false,
      chk_esp_9: false,
      chk_esp_10: false,
      selector_cantidades,
    },
  },

  Bebidas: {
    screen: "Bebidas",
    data: {
      chk_beb_1: false,
      chk_beb_2: false,
      chk_beb_3: false,
      chk_beb_4: false,
      chk_beb_5: false,
      chk_beb_6: false,
      chk_beb_7: false,
      chk_beb_8: false,
      chk_beb_9: false,
      chk_beb_10: false,
      chk_beb_11: false,
      chk_beb_12: false,
      chk_beb_13: false,
      chk_beb_14: false,
      chk_beb_15: false,
      chk_beb_16: false,
      chk_beb_17: false,
      chk_beb_18: false,
      chk_beb_19: false,
      chk_beb_20: false,
      chk_beb_21: false,
      chk_beb_22: false,
      chk_beb_23: false,
      chk_beb_24: false,
      chk_beb_25: false,
      chk_beb_26: false,
      selector_cantidades,
    },
  },

  Resumen: {
    screen: "Resumen",
    data: {},
  },

  Formulario: {
    screen: "Formulario",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
