import { selector_cantidades } from "./components.js";

export const SCREEN_RESPONSES = {
  Inicio: {
    screen: "Inicio",
    data: {
      chk_entradas: false,
      chk_pastas: false,
      chk_parrilla: false,
      chk_pesca: false,
      chk_pizzas: false,
      chk_postres: false,
    },
  },

  Productos: {
    screen: "Productos",
    data: {
      chk_entradas: false,
      chk_pastas: false,
      chk_parrilla: false,
      chk_pesca: false,
      chk_pizzas: false,
      chk_postres: false,
      chk_entrada_1: false,
      chk_entrada_2: false,
      chk_entrada_3: false,
      chk_entrada_4: false,
      chk_entrada_5: false,
      chk_pasta_1: false,
      chk_pasta_2: false,
      chk_pasta_3: false,
      chk_pasta_4: false,
      chk_pasta_5: false,
      chk_parrilla_1: false,
      chk_parrilla_2: false,
      chk_parrilla_3: false,
      chk_parrilla_4: false,
      chk_parrilla_5: false,
      chk_parrilla_6: false,
      chk_parrilla_7: false,
      chk_parrilla_8: false,
      chk_parrilla_9: false,
      chk_parrilla_10: false,
      chk_pesca_1: false,
      chk_pesca_2: false,
      chk_pesca_3: false,
      chk_pesca_4: false,
      chk_pizza_1: false,
      chk_pizza_2: false,
      chk_pizza_3: false,
      chk_pos_1: false,
      chk_pos_2: false,
      chk_pos_3: false,
      chk_pos_4: false,
      chk_pos_5: false,
    },
  },

  Cantidades: {
    screen: "Cantidades",
    data: {
      chk_entrada_1: false,
      chk_entrada_2: false,
      chk_entrada_3: false,
      chk_entrada_4: false,
      chk_entrada_5: false,
      chk_pasta_1: false,
      chk_pasta_2: false,
      chk_pasta_3: false,
      chk_pasta_4: false,
      chk_pasta_5: false,
      chk_parrilla_1: false,
      chk_parrilla_2: false,
      chk_parrilla_3: false,
      chk_parrilla_4: false,
      chk_parrilla_5: false,
      chk_parrilla_6: false,
      chk_parrilla_7: false,
      chk_parrilla_8: false,
      chk_parrilla_9: false,
      chk_parrilla_10: false,
      chk_pesca_1: false,
      chk_pesca_2: false,
      chk_pesca_3: false,
      chk_pesca_4: false,
      chk_pizza_1: false,
      chk_pizza_2: false,
      chk_pizza_3: false,
      chk_pos_1: false,
      chk_pos_2: false,
      chk_pos_3: false,
      chk_pos_4: false,
      chk_pos_5: false,

      selector_cantidades,
    },
  },

  Bebidas: {
    screen: "Bebidas",
    data: {
      chk_beb_1: false,
      chk_beb_2: false,
      chk_beb_3: false,
      chk_beb_4: false,
      chk_beb_5: false,
      chk_beb_6: false,
      chk_beb_7: false,
      chk_beb_8: false,
      chk_beb_9: false,
      chk_beb_10: false,
      chk_beb_11: false,
      chk_beb_12: false,
      chk_beb_13: false,
      chk_beb_14: false,
      chk_beb_15: false,

      selector_cantidades,
    },
  },

  Resumen: {
    screen: "Resumen",
    data: {},
  },

  Formulario: {
    screen: "Formulario",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
