import { selector_cantidades } from "./components.js";

export const SCREEN_RESPONSES = {
  Inicio: {
    screen: "Inicio",
    data: {
      chk_entradas: false,
      chk_sugerencias: false,
      chk_arroces: false,
      chk_pastas: false,
      chk_parrilla: false,
      chk_horno: false,
      chk_pesca: false,
      chk_pizzas: false,
      chk_postres: false,
    },
  },

  Productos: {
    screen: "Productos",
    data: {
      chk_entradas: false,
      chk_sugerencias: false,
      chk_arroces: false,
      chk_pastas: false,
      chk_parrilla: false,
      chk_horno: false,
      chk_pesca: false,
      chk_pizzas: false,
      chk_postres: false,
      chk_entrada_1: false,
      chk_entrada_2: false,
      chk_entrada_3: false,
      chk_entrada_4: false,
      chk_entrada_5: false,
      chk_entrada_6: false,
      chk_entrada_7: false,
      chk_entrada_8: false,
      chk_entrada_9: false,
      chk_entrada_10: false,
      chk_sug_1: false,
      chk_sug_2: false,
      chk_sug_3: false,
      chk_sug_4: false,
      chk_sug_5: false,
      chk_sug_6: false,
      chk_sug_7: false,
      chk_sug_8: false,
      chk_sug_9: false,
      chk_sug_10: false,
      chk_sug_11: false,
      chk_sug_12: false,
      chk_sug_13: false,
      chk_sug_14: false,
      chk_sug_15: false,
      chk_sug_16: false,
      chk_sug_18: false,
      chk_sug_19: false,
      chk_sug_20: false,
      chk_sug_21: false,
      chk_sug_22: false,
      chk_sug_23: false,
      chk_sug_24: false,
      chk_sug_25: false,
      chk_sug_26: false,
      chk_sug_27: false,
      chk_sug_28: false,
      chk_sug_29: false,
      chk_sug_30: false,
      chk_sug_31: false,
      chk_sug_32: false,
      chk_sug_33: false,
      chk_sug_34: false,
      chk_sug_35: false,
      chk_sug_36: false,
      chk_sug_37: false,
      chk_sug_38: false,
      chk_ens_1: false,
      chk_ens_2: false,
      chk_ens_3: false,
      chk_pos_1: false,
      chk_pos_2: false,
      chk_pos_3: false,
      chk_pos_4: false,
      chk_pos_5: false,
      chk_pos_6: false,
      chk_pos_7: false,
      chk_pos_8: false,
      chk_pos_9: false,
      chk_pos_10: false,
    },
  },

  Cantidades: {
    screen: "Cantidades",
    data: {
      chk_entrada_1: false,
      chk_entrada_2: false,
      chk_entrada_3: false,
      chk_entrada_4: false,
      chk_entrada_5: false,
      chk_entrada_6: false,
      chk_entrada_7: false,
      chk_entrada_8: false,
      chk_entrada_9: false,
      chk_entrada_10: false,
      chk_sug_1: false,
      chk_sug_2: false,
      chk_sug_3: false,
      chk_sug_4: false,
      chk_sug_5: false,
      chk_sug_6: false,
      chk_sug_7: false,
      chk_sug_8: false,
      chk_sug_9: false,
      chk_sug_10: false,
      chk_sug_11: false,
      chk_sug_12: false,
      chk_sug_13: false,
      chk_sug_14: false,
      chk_sug_15: false,
      chk_sug_16: false,
      chk_sug_18: false,
      chk_sug_19: false,
      chk_sug_20: false,
      chk_sug_21: false,
      chk_sug_22: false,
      chk_sug_23: false,
      chk_sug_24: false,
      chk_sug_25: false,
      chk_sug_26: false,
      chk_sug_27: false,
      chk_sug_28: false,
      chk_sug_29: false,
      chk_sug_30: false,
      chk_sug_31: false,
      chk_sug_32: false,
      chk_sug_33: false,
      chk_sug_34: false,
      chk_sug_35: false,
      chk_sug_36: false,
      chk_sug_37: false,
      chk_sug_38: false,
      chk_ens_1: false,
      chk_ens_2: false,
      chk_ens_3: false,
      chk_pos_1: false,
      chk_pos_2: false,
      chk_pos_3: false,
      chk_pos_4: false,
      chk_pos_5: false,
      chk_pos_6: false,
      chk_pos_7: false,
      chk_pos_8: false,
      chk_pos_9: false,
      chk_pos_10: false,

      selector_cantidades,
    },
  },

  Bebidas: {
    screen: "Bebidas",
    data: {
      chk_beb_1: false,
      chk_beb_2: false,
      chk_beb_3: false,
      chk_beb_4: false,
      chk_beb_5: false,
      chk_beb_6: false,
      chk_beb_7: false,
      chk_beb_8: false,
      chk_beb_9: false,
      chk_beb_10: false,
      chk_beb_11: false,
      chk_beb_12: false,
      chk_beb_13: false,

      selector_cantidades,
    },
  },

  Resumen: {
    screen: "Resumen",
    data: {},
  },

  Formulario: {
    screen: "Formulario",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
